apiVersion: resource.sop.huawei.com/v1alpha1
kind: Oenuma
metadata:
  name: podafi
  namespace: tcs
spec:
  name: testapp1
  replicas: 2
  updateenable: "disable"
  node: 
    - name: 
        "node"
      numa:
        - numaNum: 0
          cpuset: "0-1"
          memset: "0"
      podAffinity:
        - numaNum: 0
          podName: "nginx-deployment-d6b48c57d-5cpl6"
          namespace: "default"
        - numaNum: 0
          podName: "wrk-deployment-e5v48a24d-5aex6"
          namespace: "default"
