// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.11
// source: podaffinity.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullRequest) Reset() {
	*x = NullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podaffinity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullRequest) ProtoMessage() {}

func (x *NullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podaffinity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullRequest.ProtoReflect.Descriptor instead.
func (*NullRequest) Descriptor() ([]byte, []int) {
	return file_podaffinity_proto_rawDescGZIP(), []int{0}
}

type NumaNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumaNumer int64  `protobuf:"varint,1,opt,name=numaNumer,proto3" json:"numaNumer,omitempty"`
	Cpuset    string `protobuf:"bytes,2,opt,name=cpuset,proto3" json:"cpuset,omitempty"`
	Memset    string `protobuf:"bytes,3,opt,name=memset,proto3" json:"memset,omitempty"`
}

func (x *NumaNode) Reset() {
	*x = NumaNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podaffinity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumaNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumaNode) ProtoMessage() {}

func (x *NumaNode) ProtoReflect() protoreflect.Message {
	mi := &file_podaffinity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumaNode.ProtoReflect.Descriptor instead.
func (*NumaNode) Descriptor() ([]byte, []int) {
	return file_podaffinity_proto_rawDescGZIP(), []int{1}
}

func (x *NumaNode) GetNumaNumer() int64 {
	if x != nil {
		return x.NumaNumer
	}
	return 0
}

func (x *NumaNode) GetCpuset() string {
	if x != nil {
		return x.Cpuset
	}
	return ""
}

func (x *NumaNode) GetMemset() string {
	if x != nil {
		return x.Memset
	}
	return ""
}

type NumaInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid     bool        `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	NumaNodes []*NumaNode `protobuf:"bytes,2,rep,name=numaNodes,proto3" json:"numaNodes,omitempty"`
}

func (x *NumaInfoResponse) Reset() {
	*x = NumaInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podaffinity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumaInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumaInfoResponse) ProtoMessage() {}

func (x *NumaInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podaffinity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumaInfoResponse.ProtoReflect.Descriptor instead.
func (*NumaInfoResponse) Descriptor() ([]byte, []int) {
	return file_podaffinity_proto_rawDescGZIP(), []int{2}
}

func (x *NumaInfoResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *NumaInfoResponse) GetNumaNodes() []*NumaNode {
	if x != nil {
		return x.NumaNodes
	}
	return nil
}

type Pod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerdIDs []string `protobuf:"bytes,1,rep,name=containerdIDs,proto3" json:"containerdIDs,omitempty"`
	Uid           string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	PodName       string   `protobuf:"bytes,3,opt,name=podName,proto3" json:"podName,omitempty"`
	PodNamespace  string   `protobuf:"bytes,4,opt,name=podNamespace,proto3" json:"podNamespace,omitempty"`
}

func (x *Pod) Reset() {
	*x = Pod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podaffinity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_podaffinity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_podaffinity_proto_rawDescGZIP(), []int{3}
}

func (x *Pod) GetContainerdIDs() []string {
	if x != nil {
		return x.ContainerdIDs
	}
	return nil
}

func (x *Pod) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Pod) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Pod) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

type AffinityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pods []*Pod `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
}

func (x *AffinityRequest) Reset() {
	*x = AffinityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podaffinity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AffinityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffinityRequest) ProtoMessage() {}

func (x *AffinityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podaffinity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffinityRequest.ProtoReflect.Descriptor instead.
func (*AffinityRequest) Descriptor() ([]byte, []int) {
	return file_podaffinity_proto_rawDescGZIP(), []int{4}
}

func (x *AffinityRequest) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type AffinityGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumaNumer int64  `protobuf:"varint,1,opt,name=numaNumer,proto3" json:"numaNumer,omitempty"`
	Pods      []*Pod `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
}

func (x *AffinityGroup) Reset() {
	*x = AffinityGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podaffinity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AffinityGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffinityGroup) ProtoMessage() {}

func (x *AffinityGroup) ProtoReflect() protoreflect.Message {
	mi := &file_podaffinity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffinityGroup.ProtoReflect.Descriptor instead.
func (*AffinityGroup) Descriptor() ([]byte, []int) {
	return file_podaffinity_proto_rawDescGZIP(), []int{5}
}

func (x *AffinityGroup) GetNumaNumer() int64 {
	if x != nil {
		return x.NumaNumer
	}
	return 0
}

func (x *AffinityGroup) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type AffinityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AffinityGroup []*AffinityGroup `protobuf:"bytes,1,rep,name=affinityGroup,proto3" json:"affinityGroup,omitempty"`
}

func (x *AffinityResponse) Reset() {
	*x = AffinityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podaffinity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AffinityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffinityResponse) ProtoMessage() {}

func (x *AffinityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podaffinity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffinityResponse.ProtoReflect.Descriptor instead.
func (*AffinityResponse) Descriptor() ([]byte, []int) {
	return file_podaffinity_proto_rawDescGZIP(), []int{6}
}

func (x *AffinityResponse) GetAffinityGroup() []*AffinityGroup {
	if x != nil {
		return x.AffinityGroup
	}
	return nil
}

var File_podaffinity_proto protoreflect.FileDescriptor

var file_podaffinity_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6f, 0x64, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x4e, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x58, 0x0a, 0x08, 0x4e, 0x75, 0x6d, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x61, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x61, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x70, 0x75, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x70,
	0x75, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x73, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x73, 0x65, 0x74, 0x22, 0x51, 0x0a, 0x10,
	0x4e, 0x75, 0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x61, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e, 0x75, 0x6d, 0x61,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22,
	0x7b, 0x0a, 0x03, 0x50, 0x6f, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x64, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x49, 0x44, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6f, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x2b, 0x0a, 0x0f,
	0x41, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e,
	0x50, 0x6f, 0x64, 0x52, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x0d, 0x41, 0x66, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75,
	0x6d, 0x61, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e,
	0x75, 0x6d, 0x61, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x04, 0x70, 0x6f, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x50, 0x6f, 0x64, 0x52, 0x04, 0x70, 0x6f,
	0x64, 0x73, 0x22, 0x48, 0x0a, 0x10, 0x41, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0d, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x41, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0d, 0x61,
	0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x32, 0x81, 0x01, 0x0a,
	0x10, 0x50, 0x6f, 0x64, 0x41, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x41, 0x77, 0x61, 0x72,
	0x65, 0x12, 0x34, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x61, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x6e, 0x6f, 0x66, 0x12, 0x0c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x4e, 0x75, 0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x64, 0x41, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x10, 0x2e, 0x41, 0x66, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x41, 0x66,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_podaffinity_proto_rawDescOnce sync.Once
	file_podaffinity_proto_rawDescData = file_podaffinity_proto_rawDesc
)

func file_podaffinity_proto_rawDescGZIP() []byte {
	file_podaffinity_proto_rawDescOnce.Do(func() {
		file_podaffinity_proto_rawDescData = protoimpl.X.CompressGZIP(file_podaffinity_proto_rawDescData)
	})
	return file_podaffinity_proto_rawDescData
}

var file_podaffinity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_podaffinity_proto_goTypes = []any{
	(*NullRequest)(nil),      // 0: NullRequest
	(*NumaNode)(nil),         // 1: NumaNode
	(*NumaInfoResponse)(nil), // 2: NumaInfoResponse
	(*Pod)(nil),              // 3: Pod
	(*AffinityRequest)(nil),  // 4: AffinityRequest
	(*AffinityGroup)(nil),    // 5: AffinityGroup
	(*AffinityResponse)(nil), // 6: AffinityResponse
}
var file_podaffinity_proto_depIdxs = []int32{
	1, // 0: NumaInfoResponse.numaNodes:type_name -> NumaNode
	3, // 1: AffinityRequest.pods:type_name -> Pod
	3, // 2: AffinityGroup.pods:type_name -> Pod
	5, // 3: AffinityResponse.affinityGroup:type_name -> AffinityGroup
	0, // 4: PodAffinityAware.GetNumaNodeInof:input_type -> NullRequest
	4, // 5: PodAffinityAware.GetPodAffinity:input_type -> AffinityRequest
	2, // 6: PodAffinityAware.GetNumaNodeInof:output_type -> NumaInfoResponse
	6, // 7: PodAffinityAware.GetPodAffinity:output_type -> AffinityResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_podaffinity_proto_init() }
func file_podaffinity_proto_init() {
	if File_podaffinity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_podaffinity_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podaffinity_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NumaNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podaffinity_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NumaInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podaffinity_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Pod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podaffinity_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AffinityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podaffinity_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AffinityGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podaffinity_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AffinityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_podaffinity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podaffinity_proto_goTypes,
		DependencyIndexes: file_podaffinity_proto_depIdxs,
		MessageInfos:      file_podaffinity_proto_msgTypes,
	}.Build()
	File_podaffinity_proto = out.File
	file_podaffinity_proto_rawDesc = nil
	file_podaffinity_proto_goTypes = nil
	file_podaffinity_proto_depIdxs = nil
}
